#########################################
# Yeh's Ruleset
# Last Updated: 2026-4-17T22:00:00Z
# Size: 9
# License: GNU 3.0
# GitHub: https://github.com/perryyeh/Surge
#########################################
DOMAIN-SUFFIX,oaistatic.com
DOMAIN-SUFFIX,chatgpt.com
DOMAIN-SUFFIX,sora.com
DOMAIN-SUFFIX,chat.com
DOMAIN-SUFFIX,ai.com
DOMAIN,api.openai.com
DOMAIN-SUFFIX,oaiusercontent.com
DOMAIN-SUFFIX,openaiusercontent.com
DOMAIN,api.github.com