#########################################
# Yeh's Ruleset
# Last Updated: 2025-04-18T19:00:00Z
# Size: 1
# License: GNU 3.0
# GitHub: https://github.com/perryyeh/Surge
#########################################
DOMAIN-SUFFIX,apple-relay.apple.com
################## EOF ##################