#########################################
# Yeh's Ruleset
# Last Updated: 2026-08-04T02:59:33Z
# Size: 19
# License: GNU 3.0
# GitHub: https://github.com/perryyeh/Surge
#########################################
DOMAIN-SUFFIX,apple-relay.akamaized.net
DOMAIN-SUFFIX,apple-relay.apple.com
DOMAIN-SUFFIX,apple-relay.cloudflare.com
DOMAIN-SUFFIX,apple-relay.fastly-edge.com
DOMAIN-SUFFIX,apple-relay.mask.apple-dns.net
DOMAIN-SUFFIX,push.apple.com
DOMAIN-SUFFIX,cp4.cloudflare.com
DOMAIN-SUFFIX,guzzoni.apple.com
DOMAIN-SUFFIX,smoot.apple.com
DOMAIN-SUFFIX,gspe1-ssl.ls.apple.com
DOMAIN,mask-api.fe.apple-dns.net
DOMAIN,mask-api.icloud.com
DOMAIN,mask-t.apple-dns.net
DOMAIN,mask.apple-dns.net
DOMAIN-SUFFIX,apps.mzstatic.com
DOMAIN-SUFFIX,gateway.icloud.com
DOMAIN-SUFFIX,ls.apple.com
DOMAIN-SUFFIX,mask-h2.icloud.com
DOMAIN-SUFFIX,mask.icloud.com
################## EOF ##################