#########################################
# Yeh's Ruleset
# Last Updated: 2025-10-28T22:00:00Z
# Size: 15
# License: GNU 3.0
# GitHub: https://github.com/perryyeh/Surge
#########################################
# 手机联合登陆
DOMAIN-SUFFIX,cmpassport.com
DOMAIN-SUFFIX,hmrz.wo.cn
DOMAIN-SUFFIX,wostore.cn
DOMAIN-SUFFIX,wosms.cn
DOMAIN-SUFFIX,nisportal.10010.com
DOMAIN-SUFFIX,enrichgw.10010.com
DOMAIN-SUFFIX,e.189.cn
DOMAIN-SUFFIX,id6.me
DOMAIN-SUFFIX,volces.com
DOMAIN-SUFFIX,ssports.com
DOMAIN-SUFFIX,zijieapi.com
DOMAIN-SUFFIX,ossapi.baidu.com
# ali 手机联合登陆
DOMAIN-SUFFIX,dypnsapi.aliyuncs.com
DOMAIN-SUFFIX,vpp-license-proxy.aliyuncs.com
DOMAIN-SUFFIX,sdk.beizi.biz
################## EOF ##################