#########################################
# Yeh's Ruleset
# Last Updated: 2026-1-3T00:00:00Z
# Size: 5
# License: GNU 3.0
# GitHub: https://github.com/perryyeh/Surge
#########################################
DOMAIN-SUFFIX,accounts.google.com
DOMAIN-SUFFIX,antigravity-unleash.goog
DOMAIN-SUFFIX,googleapis.com
DOMAIN-SUFFIX,googleusercontent.com
DOMAIN-SUFFIX,googletagmanager.com
DOMAIN-SUFFIX,gstatic.com
DOMAIN-SUFFIX,csp.withgoogle.com
DOMAIN-SUFFIX,ogs.google.com
DOMAIN-SUFFIX,google-ohttp-relay-safebrowsing.fastly-edge.com
DOMAIN-SUFFIX,safebrowsing.google.com
DOMAIN-SUFFIX,apis.google.com
DOMAIN-SUFFIX,signaler-pa.clients6.google.com
################## EOF ##################