#########################################
# Yeh's Ruleset
# Last Updated: 2026-5-29T00:00:00Z
# Size: 12
# License: GNU 3.0
# GitHub: https://github.com/perryyeh/Surge
#########################################
DOMAIN-SUFFIX,googlevideo.com
DOMAIN-SUFFIX,withyoutube.com
DOMAIN-SUFFIX,youtube-nocookie.com
DOMAIN-SUFFIX,youtube.com
DOMAIN-SUFFIX,youtubeeducation.com
DOMAIN-SUFFIX,youtubegaming.com
DOMAIN-SUFFIX,youtubekids.com
DOMAIN,youtube.googleapis.com
DOMAIN,youtubei.googleapis.com
DOMAIN,optimizationguide-pa.googleapis.com
DOMAIN,ytimg.com
DOMAIN,ggpht.com
################## EOF ##################