#########################################
# Yeh's Ruleset
# Last Updated: 2026-1-1T12:00:00Z
# Size: 3
# License: GNU 3.0
# GitHub: https://github.com/perryyeh/Surge
#########################################
DOMAIN-SUFFIX,antigravity-unleash.goog
DOMAIN-SUFFIX,googleapis.com
DOMAIN-SUFFIX,googleusercontent.com
DOMAIN-SUFFIX,google.com
################## EOF ##################