#########################################
# Yeh's Ruleset
# Last Updated: 2026-5-28T01:00:00Z
# Size: 8
# License: GNU 3.0
# GitHub: https://github.com/perryyeh/Surge
#########################################
DOMAIN-SUFFIX,openai.com
DOMAIN-SUFFIX,chatgpt.com
DOMAIN-SUFFIX,oaistatic.com
DOMAIN-SUFFIX,sora.com
DOMAIN-SUFFIX,chat.com
DOMAIN-SUFFIX,ai.com
DOMAIN-SUFFIX,oaiusercontent.com
DOMAIN-SUFFIX,openaiusercontent.com