#########################################
# Yeh's Ruleset
# Last Updated: 2026-06-24T00:00:00Z
# Size: 4
# License: GNU 3.0
# GitHub: https://github.com/perryyeh/Surge
#########################################
# reddit
DOMAIN-SUFFIX,reddit.com
DOMAIN-SUFFIX,redd.it
# media
DOMAIN-SUFFIX,medium.com
# v2ex
DOMAIN-SUFFIX, v2ex.com
DOMAIN-SUFFIX, v2ex.pro
################## EOF ##################