#########################################
# Yeh's Ruleset
# Last Updated: 2025-04-18T19:00:00Z
# Size: 6
# License: GNU 3.0
# GitHub: https://github.com/perryyeh/Surge
#########################################
# paypal
DOMAIN-SUFFIX,paypal.com
DOMAIN-SUFFIX,paypalobjects.com
DOMAIN-SUFFIX,aypal-mktg.com
# reddit
DOMAIN-SUFFIX,reddit.com
DOMAIN-SUFFIX,redd.it
# tiktok
DOMAIN-SUFFIX,pitaya-clientai.com
################## EOF ##################