#########################################
# Yeh's Ruleset
# Last Updated: 2026-10-07T23:00:00Z
# Size: 18
# License: GNU 3.0
# GitHub: https://github.com/perryyeh/Surge
#########################################
# stock
DOMAIN-SUFFIX,interactivebrokers.com
DOMAIN-SUFFIX,ibllc.com
DOMAIN-SUFFIX,ibkr.com
# paypal
DOMAIN-SUFFIX,paypal.com
DOMAIN-SUFFIX,paypalobjects.com
DOMAIN-SUFFIX,aypal-mktg.com
# stripe link
DOMAIN-SUFFIX,stripe.com
DOMAIN-SUFFIX,stripe.network
DOMAIN-SUFFIX,stripecdn.com
DOMAIN-SUFFIX,stripeassets.com
DOMAIN-SUFFIX,hcaptcha.com
DOMAIN-SUFFIX,link.com
# tello
DOMAIN-SUFFIX,tello.com
DOMAIN-SUFFIX,mmsmvmo.com
# ebay
DOMAIN-SUFFIX,ebay.com
DOMAIN-SUFFIX,ebayimg.com
DOMAIN-SUFFIX,ebaystatic.com
DOMAIN-SUFFIX,pinimg.com