#########################################
# Yeh's Ruleset
# Last Updated: 2026-8-14T21:00:00Z
# Size: 11
# License: GNU 3.0
# GitHub: https://github.com/perryyeh/Surge
#########################################
# paypal
DOMAIN-SUFFIX,paypal.com
DOMAIN-SUFFIX,paypalobjects.com
DOMAIN-SUFFIX,aypal-mktg.com
# stripe link
DOMAIN-SUFFIX,stripe.com
DOMAIN-SUFFIX,stripe.network
DOMAIN-SUFFIX,stripecdn.com
DOMAIN-SUFFIX,stripeassets.com
DOMAIN-SUFFIX,hcaptcha.com
DOMAIN-SUFFIX,link.com
# stock
DOMAIN-SUFFIX,interactivebrokers.com
DOMAIN-SUFFIX,ibllc.com
DOMAIN-SUFFIX,ibkr.com
################## EOF ##################