#time
DOMAIN-SUFFIX,ntp.org
DOMAIN-SUFFIX,time.apple.com
DOMAIN-SUFFIX,time.asia.apple.com
DOMAIN-SUFFIX,time.cloudflare.com
#apple
DOMAIN-SUFFIX,cdn-apple.com
#cloudflare
DOMAIN-SUFFIX,api.cloudflare.com
# proxy
DOMAIN-SUFFIX,gorelay.xyz
# bank
DOMAIN-SUFFIX,95516.com
DOMAIN-SUFFIX,boc.cn
DOMAIN-SUFFIX,cgbchina.com
DOMAIN-SUFFIX,cmbchina.com
DOMAIN-SUFFIX,hsbc.com.cn
DOMAIN-SUFFIX,hsbc.com.hk
DOMAIN-SUFFIX,hsbc.com
DOMAIN-SUFFIX,hsbc.com.sg
DOMAIN-SUFFIX,hsbc.co.uk
DOMAIN-SUFFIX,validate.perfdrive.com
# wechat hk pay
DOMAIN-SUFFIX,arcot.com
# stock
DOMAIN-SUFFIX,mysmartadvisor.com
# oyunfor 土耳其
DOMAIN-SUFFIX,oyunfor.com
# DOMAIN-SUFFIX,iyzico.com
# qq
DOMAIN-SUFFIX,ntlogin.qq.com
DOMAIN-SUFFIX,fairplay.l.qq.com
# mi
DOMAIN-SUFFIX,io.mi.com
DOMAIN-SUFFIX,hd.mi.com
DOMAIN-SUFFIX,chat.xiaomi.net
# 欧洲签证
DOMAIN-SUFFIX,visa.vfsglobal.com
# 误杀
DOMAIN-SUFFIX,amazon.cn
DOMAIN,fls-cn.amazon.com
DOMAIN,unagi-cn.amazon.com
DOMAIN-SUFFIX,amazonaws.com
DOMAIN-SUFFIX,amazontrust.com
DOMAIN-SUFFIX,data.bilibili.com
DOMAIN-SUFFIX,cm.mediav.com
DOMAIN-SUFFIX,ckm.aty.sohu.com