DOMAIN-KEYWORD,mp4files
DOMAIN-SUFFIX,353hui.cn
DOMAIN-SUFFIX,qdtechworld.com
DOMAIN-SUFFIX,ppmh84.com
DOMAIN-SUFFIX,wenyinsz.cn
DOMAIN-SUFFIX,ggylevt.cn
DOMAIN-SUFFIX,vejian.cn
DOMAIN-SUFFIX,wer4646.cn
DOMAIN-SUFFIX,lnxyss.cn
DOMAIN-SUFFIX,lixuandz6.cn
DOMAIN-SUFFIX,kalay.net.cn
DOMAIN-SUFFIX,ipinfo.io
DOMAIN-SUFFIX,ip-api.com
DOMAIN-SUFFIX,ux.1cn.com
DOMAIN-SUFFIX,beizi.biz
DOMAIN-SUFFIX,linkedme.cc
DOMAIN-SUFFIX,bugsnag.com
DOMAIN-SUFFIX,services.mozilla.com
# DOMAIN-SUFFIX,geetest.com
# DOMAIN-SUFFIX,mzstatic.com
# facebook
DOMAIN-SUFFIX,graph.facebook.com
# ctrip
DOMAIN-SUFFIX,ma-adx.ctrip.com
DOMAIN-SUFFIX,s.c-ctrip.com
DOMAIN-SUFFIX,ak-s.tripcdn.com
# amap
# DOMAIN-SUFFIX,restapi.amap.com
DOMAIN-SUFFIX,tls-amap.dingtalk.com
# apple
DOMAIN-SUFFIX,icloud-analysis.com
# DOMAIN-SUFFIX,metrics.icloud.com
# DOMAIN-SUFFIX,mesu.apple.com
DOMAIN-SUFFIX,iadsdk.apple.com
DOMAIN-SUFFIX,appcenter.ms
DOMAIN-SUFFIX,apphub.com
# google
DOMAIN-SUFFIX,adservice.google.cn
# alibaba
DOMAIN-SUFFIX,asc.m.taobao.com
DOMAIN-SUFFIX,gaode-acs.m.taobao.com
DOMAIN-SUFFIX,aid.m.taobao.com
DOMAIN-SUFFIX,wvcfg.alicdn.com
DOMAIN-SUFFIX,alimama.com
DOMAIN-SUFFIX,fleamarket.taobao.com
DOMAIN-SUFFIX,loggw.alipay.com
# qq
DOMAIN-SUFFIX,qamp.qq.com
DOMAIN-SUFFIX,rmonitor.qq.com
# xiaomi
DOMAIN-SUFFIX,stat.youpin.mi.comm
DOMAIN-SUFFIX,hd.mina.mi.com
DOMAIN-SUFFIX,imgopen.xmcdn.com
# zhihu
DOMAIN-SUFFIX,zhihu-web-analytics.zhihu.com

