#dns
DOMAIN-SUFFIX,cloudflare-dns.com
DOMAIN-SUFFIX,dns.google
# nintendo
DOMAIN-SUFFIX,nintendo.com
DOMAIN-SUFFIX,nintendo.com.hk
# github
DOMAIN-SUFFIX,github.com
DOMAIN-SUFFIX,githubusercontent.com
# 自定义域名
DOMAIN-SUFFIX,raw.githubusercontent.com
DOMAIN-SUFFIX,flightradar24.com
DOMAIN-SUFFIX,archive.org
DOMAIN-SUFFIX,openapi.com
DOMAIN-SUFFIX,geetest.com
DOMAIN-SUFFIX,ui.com
DOMAIN-SUFFIX,evernote.com
DOMAIN-SUFFIX,gitgoogle.com
DOMAIN-SUFFIX,t.co
# tools
DOMAIN-SUFFIX,ipinfo.io
# host
DOMAIN-SUFFIX,vultr.com
DOMAIN-SUFFIX,stripecdn.com
# ss server
DOMAIN-SUFFIX,wcc.best
DOMAIN-SUFFIX,v2tun-163cdn.com
DOMAIN-SUFFIX,sublink.dev
# bt
DOMAIN-SUFFIX,thepiratebay.org
DOMAIN-SUFFIX,1337x.to
DOMAIN-SUFFIX,eztv.re
DOMAIN-SUFFIX,yts.mx
DOMAIN-SUFFIX,rarbg.to
DOMAIN-SUFFIX,demonoid.is
DOMAIN-SUFFIX,nyaa.si
DOMAIN-SUFFIX,bt4g.org
DOMAIN-SUFFIX,magnetdl.com
DOMAIN-SUFFIX,zooqle.com
DOMAIN-SUFFIX,ettv.be
DOMAIN-SUFFIX,glodls.to
DOMAIN-SUFFIX,Torlock2.com
DOMAIN-SUFFIX,proxybb.com
DOMAIN-SUFFIX,edvok.com
DOMAIN-SUFFIX,dmhy.org
DOMAIN-SUFFIX,pirateiro.eu
DOMAIN-SUFFIX,btdig.com
DOMAIN-SUFFIX,rarbg.to
# other
DOMAIN-SUFFIX,notion.so
DOMAIN-SUFFIX,bing.com
DOMAIN-SUFFIX,imgur.com
DOMAIN-SUFFIX,lvv2.com
DOMAIN-SUFFIX,linux.do
DOMAIN-SUFFIX,v2ex.com
DOMAIN-SUFFIX,v2ex.co
DOMAIN-SUFFIX,loli.net
DOMAIN-SUFFIX,bang-olufsen.com
DOMAIN-SUFFIX,onfastspring.com
DOMAIN-SUFFIX,whatismyipaddress.com
DOMAIN-SUFFIX,serif.com
DOMAIN-SUFFIX,wikipedia.org
# media
DOMAIN-SUFFIX,medium.com
# surge
DOMAIN-SUFFIX,nssurge.com